import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import React from 'react';
import {
  faEnvelope,
  faAddressCard,
  faFileArchive,
  faBarChart,
  faArrowAltCircleDown,
  faArrowAltCircleLeft,
  faArrowAltCircleRight,
  faArrowAltCircleUp,
  faBell,
  faBookmark,
  faBuilding,
  faCalendar,
  faCaretSquareDown,
  faCaretSquareLeft,
  faCaretSquareRight,
  faCaretSquareUp,
  faChartBar,
  faCheckCircle,
  faCheckSquare,
  faCircle,
  faCircleCheck,
  faCircleDown,
  faCircleDot,
  faCircleRight,
  faCircleLeft,
  faCirclePause,
  faCirclePlay,
  faClipboard,
  faClock,
  faClosedCaptioning,
  faComment,
  faCompass,
  faCopy,
  faCopyright,
  faEdit,
  faEye,
  faEyeSlash,
  faFaceSmile,
  faFile,
  faFileExcel,
  faFilePdf,
  faFileText,
  faFileVideo,
  faHand,
  faImage,
  faKeyboard,
  faLightbulb,
  faMap,
  faMessage,
  faPaste,
  faSave,
  faSquare,
  faStar,
  faThumbsDown,
  faThumbsUp,
  faTrashCan,
  faUser,
  faUserCircle,
  faWindowClose,
  faWindowMaximize,
  faWindowMinimize,
  faWindowRestore,
  faXmarkCircle,
  faFileZipper,
  faDizzy,
  IconDefinition
} from '@fortawesome/free-regular-svg-icons';

const icons: { [key: string]: IconDefinition } = {
    'Envelope': faEnvelope,
    'AddressCard': faAddressCard,
    'FileArchive': faFileArchive,
    'BarChart': faBarChart,
    'ArrowAltCircleDown': faArrowAltCircleDown,
    'ArrowAltCircleLeft': faArrowAltCircleLeft,
    'ArrowAltCircleRight': faArrowAltCircleRight,
    'ArrowAltCircleUp': faArrowAltCircleUp,
    'Bell': faBell,
    'Bookmark': faBookmark,
    'Building': faBuilding,
    'Calendar': faCalendar,
    'CaretSquareDown': faCaretSquareDown,
    'CaretSquareLeft': faCaretSquareLeft,
    'CaretSquareRight': faCaretSquareRight,
    'CaretSquareUp': faCaretSquareUp,
    'ChartBar': faChartBar,
    'CheckCircle': faCheckCircle,
    'CheckSquare': faCheckSquare,
    'Circle': faCircle,
    'CircleCheck': faCircleCheck,
    'CircleDown': faCircleDown,
    'CircleDot': faCircleDot,
    'CircleRight': faCircleRight,
    'CircleLeft': faCircleLeft,
    'CirclePause': faCirclePause,
    'CirclePlay': faCirclePlay,
    'Clipboard': faClipboard,
    'Clock': faClock,
    'ClosedCaptioning': faClosedCaptioning,
    'Comment': faComment,
    'Compass': faCompass,
    'Copy': faCopy,
    'Copyright': faCopyright,
    'Edit': faEdit,
    'Eye': faEye,
    'EyeSlash': faEyeSlash,
    'FaceSmile': faFaceSmile,
    'File': faFile,
    'FileExcel': faFileExcel,
    'FilePdf': faFilePdf,
    'FileText': faFileText,
    'FileVideo': faFileVideo,
    'Hand': faHand,
    'Image': faImage,
    'Keyboard': faKeyboard,
    'Lightbulb': faLightbulb,
    'Map': faMap,
    'Message': faMessage,
    'Paste': faPaste,
    'Save': faSave,
    'Square': faSquare,
    'Star': faStar,
    'ThumbsDown': faThumbsDown,
    'ThumbsUp': faThumbsUp,
    'TrashCan': faTrashCan,
    'User': faUser,
    'UserCircle': faUserCircle,
    'WindowClose': faWindowClose,
    'WindowMaximize': faWindowMaximize,
    'WindowMinimize': faWindowMinimize,
    'WindowRestore': faWindowRestore,
    'XmarkCircle': faXmarkCircle,
    'FileZipper': faFileZipper,
    'Dizzy': faDizzy
  };
  

  interface IconProp{
    icon: string,
    onClick?: () => void
  }

  export const Icon = ({icon = 'Envelope', onClick}: IconProp) => {
    typeof icons
    return (
      <FontAwesomeIcon onClick={onClick} style={{cursor: 'pointer'}} icon={icons[icon]}/>
    )
  }